"use client";
import { Fragment, useEffect, useMemo, useRef, useState } from "react";
import { CarFront } from "lucide-react";
const ITEMS = [
  "Amortecedor Dianteiro Direito",
  "Amortecedor Dianteiro Esquerdo",
  "Amortecedor Traseiro Direito",
  "Amortecedor Traseiro Esquerdo",
  "Mola Dianteira Direita",
  "Mola Dianteira Esquerda",
  "Mola Traseira Direita",
  "Mola Traseira Esquerda",
  "Kit do Amortecedor Dianteiro Direito",
  "Kit do Amortecedor Dianteiro Esquerdo",
  "Kit do Amortecedor Traseiro Direito",
  "Kit do Amortecedor Traseiro Esquerdo",
  "Coxim do Motor",
  "Coxim do Câmbio",
  "Braço Oscilante LD",
  "Braço Oscilante LE",
  "Bandeja Dianteira Direita",
  "Bandeja Dianteira Esquerda",
  "Bucha Diant. da Bandeja Dianteira",
  "Bucha Traseira da Bandeja Dianteira",
  "Suporte Barra Tensora LD (morceguinho)",
  "Suporte Barra Tensora LE (morceguinho)",
  "Bieleta Dianteira Direita",
  "Bieleta Dianteira Esquerda",
  "Bieleta Traseira Direita",
  "Bieleta Traseira Esquerda",
  "Pivô Dianteiro Direito",
  "Pivô Dianteiro Esquerdo",
  "Bucha Barra Estabilizadora",
  "Terminal de Direção Direito",
  "Terminal de Direção Esquerdo",
  "Terminal do Tensor",
  "Axial da Direção Direito",
  "Axial da Direção Esquerdo",
  "Cubo de Roda Dianteiro Direito",
  "Cubo de Roda Dianteiro Esquerdo",
  "Cubo de Roda Traseiro Direito",
  "Cubo de Roda Traseiro Esquerdo",
  "Rolamento de Roda Dianteiro",
  "Rolamento de Roda Traseiro",
  "Bucha do Eixo",
  "Barra de Direção",
  "Caixa de Direção",
  "Fluido de Direção",
  "Junta Homocinética Interna",
  "Junta Homocinética Externa",
  "Coifa",
  "Semi-eixo",
  "Pneu",
  "Pastilha de Freio",
  "Disco de freio",
  "Cilindro de Freio (Tras. Esq./Dir.) Mestre",
  "Sapata de freio Traseira",
  "Pastilha de freio Traseira",
  "Válvula de Pneus (Bico)",
];
const FRONT = [
    "Amortecedores dianteiros",
    "Coxim dos amortecedores",
    "Rolamentos do coxim",
    "Molas dianteiras",
    "Bandejas",
    "Buchas das bandejas",
    "Pivôs",
    "Terminais de direção",
    "Axiais de direção",
    "Bieletas",
    "Barra estabilizadora",
    "Buchas da barra estabilizadora",
    "Agregado/suporte motor",
    "Cubos de roda",
  ],
  REAR = [
    "Amortecedores traseiros",
    "Coxim traseiros",
    "Molas traseiras",
    "Buchas traseiras",
    "Eixo traseiro",
    "Braços oscilantes",
    "Barra estabilizadora traseira",
    "Cubo de roda traseiros",
  ],
  SAFE = [
    "Todos os parafusos reapertados",
    "Torque aplicado conforme fabricante",
    "Conferido aperto de rodas",
    "Conferido altura do veículo",
    "Conferido folgas",
    "Conferido vazamentos",
    "Conferido posição mola e coxins",
    "Conferido alinhamento",
    "Conferido balanceamento",
